version: "3"

services:
  mysql:
    container_name: mysql-dev
    image: mysql:5.7.26
    ports:
      - "8001:3306"
    environment:
      - "MYSQL_USER=root"
      - "MYSQL_ROOT_PASSWORD=sedes;"
      - "MYSQL_DATABASE=strapi-backend-dev"
    volumes:
      - ./database/mysql-docker-data:/var/lib/mysql
      - ./database/mysql-config.cnf:/etc/mysql/conf.d/custom.cnf
    networks:
      - app_network
    restart: always
  backend:
    container_name: backend-dev
    build:
      context: ./backend-strapi
      dockerfile: Dockerfile
      args:
        - "ENV_WORKDIR=/usr/src/backend-strapi"
    depends_on:
      - "mysql"
    command: ["./wait-for-it.sh", "mysql:8001", "--", "npm", "run", "dev"]
    environment:
      - "test=testvalue"
      - "DATABASE_PORT=8001"
      - "DATABASE_PASSWORD=sedes;"
      - "DATABASE_HOST=mysql"
      - "DATABASE_NAME=strapi-backend-dev"
    volumes:
      - ./backend-strapi:/usr/src/backend-strapi
      - /usr/src/backend-strapi/node_modules
    working_dir: /usr/src/backend-strapi
    ports:
      - "1337:1337"
    networks:
      - app_network
    restart: always

  frontend:
    container_name: frontend-dev
    build:
      context: ./frontend-next
      dockerfile: Dockerfile
      args:
        - "ENV_WORKDIR=/usr/src/frontend-next"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-next:/usr/src/frontend-next
      - /usr/src/frontend-next/node_modules
    command: ["npm", "run", "dev"]
    networks:
      - app_network
    restart: always

networks:
  app_network:
