version: "3"

services:
  mysql:
    container_name: mysql-prod
    image: mysql:5.7.26
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_DATABASE=${DB_NAME}"
    networks:
      - app_network_prod
    restart: always
    volumes:
      # see https://github.com/strapi/strapi/issues/1957 and ./mysql-init/delete...shema.sql for explanation
      # ok this is weird but now it works correctly without this entry, but I'll leave it here just in case
      # - ./database-prod/mysql-init:/docker-entrypoint-initdb.d
      - ./database-prod-data/mysql-docker-data:/var/lib/mysql
      - ./database/mysql-config.cnf:/etc/mysql/conf.d/custom.cnf
  backend:
    container_name: backend-prod
    build:
      context: ./backend-strapi
      dockerfile: Dockerfile
      args:
        - "ENV_WORKDIR=/usr/src/backend-strapi"
    depends_on:
      - "mysql"
    command:
      ["./wait-for-it.sh", "mysql:3306", "--", "npm", "run", "start:prod"]
    environment:
      - "DATABASE_PORT=3306"
      - "DATABASE_PASSWORD=${DB_PASSWORD}"
      - "DATABASE_HOST=${DB_HOST}"
      - "DATABASE_USERNAME=${DB_USER}"
      - "DATABASE_NAME=${DB_NAME}"
    volumes:
      - ./backend-strapi:/usr/src/backend-strapi
      - /usr/src/backend-strapi/node_modules
    working_dir: /usr/src/backend-strapi
    ports:
      - "1337:1337"
    networks:
      - app_network_prod
    restart: always

  frontend:
    container_name: frontend-prod
    build:
      context: ./frontend-next
      dockerfile: Dockerfile
      args:
        - "ENV_WORKDIR=/usr/src/frontend-next"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-next:/usr/src/frontend-next
      - /usr/src/frontend-next/node_modules
    command: ["npm", "run", "start:prod"]
    networks:
      - app_network_prod
    restart: always

networks:
  app_network_prod:
