version: "3"

services:
  mysql:
    container_name: CREDS-mysql-dev
    image: mysql:5.7.26
    ports:
      - 3306:3306
    environment:
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_DATABASE=${DB_NAME}"
    volumes:
      - ./database/mysql-docker-data:/var/lib/mysql
      - ./database/mysql-config.cnf:/etc/mysql/conf.d/custom.cnf
    networks:
      - CREDS_app_network
    restart: always
  backend:
    container_name: CREDS-backend-dev
    build:
      context: ./backend-strapi
      dockerfile: Dockerfile
      args:
        - "ENV_WORKDIR=/usr/src/backend-strapi"
    depends_on:
      - "mysql"
    command: ["./wait-for-it.sh", "mysql:3306", "--", "npm", "run", "dev"]
    environment:
      - "DATABASE_PORT=3306"
      - "DATABASE_PASSWORD=${DB_PASSWORD}"
      - "DATABASE_HOST=${DB_HOST}"
      - "DATABASE_USERNAME=${DB_USER}"
      - "DATABASE_NAME=${DB_NAME}"
    volumes:
      - ./backend-strapi:/usr/src/backend-strapi
      - /usr/src/backend-strapi/node_modules
    working_dir: /usr/src/backend-strapi
    ports:
      - "1337:1337"
    networks:
      - CREDS_app_network
    restart: always

  frontend:
    container_name: CREDS-frontend-dev
    build:
      context: ./frontend-next
      dockerfile: Dockerfile
      args:
        - "ENV_WORKDIR=/usr/src/frontend-next"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-next:/usr/src/frontend-next
      - /usr/src/frontend-next/node_modules
    command: ["npm", "run", "dev"]
    networks:
      - CREDS_app_network
    restart: always

  bridge:
    container_name: CREDS-bridge-dev
    build:
      context: ./bridge-express
      dockerfile: Dockerfile
      args:
        - "ENV_WORKDIR=/usr/src/bridge-express"
    ports:
      - "1234:1234"
    volumes:
      - ./bridge-express:/usr/src/fbridge-express
      - /usr/src/fbridge-express/node_modules
    command: ["npm", "start"]
    networks:
      - CREDS_app_network
    restart: always

  # In case one need to investigate database
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: "png-phpmyadmin"
  #   links:
  #     - mysql
  #   environment:
  #     PMA_HOST: mysql-dev
  #     PMA_PORT: 3306
  #   ports:
  #     - "8081:80"
  #   volumes:
  #     - /sessions
  #   networks:
  #     - CREDS_app_network

networks:
  CREDS_app_network:
